version: "3.8"

services:
  # === PostgreSQL Database ===
  postgres:
    image: postgres:latest
    container_name: duolingolite_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thanh2004
      - POSTGRES_DB=DuolingoLite
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # === ASP.NET Core Web API ===
  webapi:
    container_name: duolingolite_webapi
    build:
      context: .
      dockerfile: src/Dockerfile
      # If your Dockerfile is actually at "src/WebApi/Dockerfile", adjust path accordingly
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      # Example connection string to Postgres
      - ConnectionStrings__Postgres=Host=postgres;Database=duolingolite;Username=postgres;Password=thanh2004
      # If you need to override ASP.NET port binding
      - ASPNETCORE_URLS=http://+:8080

volumes:
  postgres_data:
